"""Parametric CAD Exporter and Geometric Computation Engine."""

from src.schemas.cad import CADParametricSpec, CADExportResponse


class CADExporter:
    """Computes physical properties and exports parametric CAD definitions."""

    @staticmethod
    def export(spec: CADParametricSpec) -> CADExportResponse:
        # Physical metric computations (dimensions in mm)
        base_vol_mm3 = spec.length_mm * spec.width_mm * spec.base_thickness_mm
        single_fin_vol_mm3 = spec.length_mm * spec.fin_thickness_mm * spec.fin_height_mm
        total_fins_vol_mm3 = spec.fin_count * single_fin_vol_mm3
        total_vol_mm3 = base_vol_mm3 + total_fins_vol_mm3

        vol_cm3 = total_vol_mm3 / 1000.0
        mass_grams = vol_cm3 * spec.material_density_g_cm3

        # Surface area computation
        # Base: bottom face (L*W) + side faces + top exposed area
        base_top_area = (spec.length_mm * spec.width_mm) - (spec.fin_count * spec.length_mm * spec.fin_thickness_mm)
        base_top_area = max(0.0, base_top_area)
        base_bottom_area = spec.length_mm * spec.width_mm
        base_sides_area = 2 * (spec.length_mm + spec.width_mm) * spec.base_thickness_mm

        # Fins: 2 * (length * height) + 2 * (thickness * height) + (length * thickness) per fin
        fin_area_single = (2 * spec.length_mm * spec.fin_height_mm) + (2 * spec.fin_thickness_mm * spec.fin_height_mm) + (spec.length_mm * spec.fin_thickness_mm)
        total_fin_area = spec.fin_count * fin_area_single

        total_area_mm2 = base_top_area + base_bottom_area + base_sides_area + total_fin_area
        total_area_cm2 = total_area_mm2 / 100.0

        # Spacing between fins
        fin_spacing_mm = (
            (spec.width_mm - (spec.fin_count * spec.fin_thickness_mm)) / (spec.fin_count - 1)
            if spec.fin_count > 1 else 0.0
        )

        # Parametric Feature Tree JSON
        feature_tree = {
            "component": spec.part_name,
            "version": "1.0",
            "units": "mm",
            "material": {
                "name": spec.material,
                "density_g_cm3": spec.material_density_g_cm3,
            },
            "features": [
                {
                    "id": "base_plate",
                    "type": "ExtrudeFeature",
                    "parameters": {
                        "length": spec.length_mm,
                        "width": spec.width_mm,
                        "thickness": spec.base_thickness_mm,
                        "origin": [0.0, 0.0, 0.0],
                    },
                },
                {
                    "id": "fin_pattern",
                    "type": "LinearPatternFeature",
                    "parameters": {
                        "fin_count": spec.fin_count,
                        "fin_length": spec.length_mm,
                        "fin_thickness": spec.fin_thickness_mm,
                        "fin_height": spec.fin_height_mm,
                        "pitch_spacing": fin_spacing_mm + spec.fin_thickness_mm,
                        "base_offset_z": spec.base_thickness_mm,
                    },
                },
            ],
            "bounding_box": {
                "x_min": 0.0,
                "x_max": spec.length_mm,
                "y_min": 0.0,
                "y_max": spec.width_mm,
                "z_min": 0.0,
                "z_max": spec.base_thickness_mm + spec.fin_height_mm,
            },
        }

        # OpenSCAD parametric representation
        openscad_script = f"""// Parametric OpenSCAD Model: {spec.part_name}
// Auto-generated by hardware-pareto-optimizer
$fn = 32;

length = {spec.length_mm};
width = {spec.width_mm};
base_thick = {spec.base_thickness_mm};
fin_h = {spec.fin_height_mm};
fin_count = {spec.fin_count};
fin_thick = {spec.fin_thickness_mm};
spacing = {fin_spacing_mm:.3f};

module heatsink() {{
    // Baseplate
    cube([length, width, base_thick]);
    
    // Fins Array
    for (i = [0 : fin_count - 1]) {{
        translate([0, i * (fin_thick + spacing), base_thick])
            cube([length, fin_thick, fin_h]);
    }}
}}

heatsink();
"""

        return CADExportResponse(
            part_name=spec.part_name,
            material=spec.material,
            computed_volume_cm3=round(vol_cm3, 4),
            computed_mass_grams=round(mass_grams, 4),
            total_surface_area_cm2=round(total_area_cm2, 4),
            feature_tree=feature_tree,
            openscad_script=openscad_script,
        )
